version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: mzegarra/jenkins:1.0.0
    ports:
      - 8080:8080
    user: "root:jenkins"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock